From node:16.15.1-slim as build
ENV NODE_OPTIONS=--max_old_space_size=8192
WORKDIR /app
COPY ./ ./

RUN yarn install --prefer-offline
RUN yarn build-lib

RUN yarn build-frontend

FROM nginx as frontendimage

COPY --chown=nginx --from=build /app/frontend/build /usr/share/nginx/html
